api:
  defaultpagingsize: 16
  maxpagingsize: 32
cache:
  adapter: memory
  enabled: true
  interval: 1m0s
  ttl: 24h0m0s
database:
  driver: sqlite3
  maxidleconns: 0
  maxlifetime: 0s
  maxopenconns: 0
  url: /db/gorm.db
log:
  base:
    encoding: console
  loggers:
    console:
      level: debug
      provider: console
mailer:
  certfile: ""
  enabled: true
  from: ""
  host: smtp.qq.com:465
  istlsenable: false
  keyfile: ""
  password: jqquapwzvqctbbed
  queuelength: 512
  sendasplaintext: false
  skipverify: true
  subjectprefix: '[ahfs]'
  usecertificate: false
  username: 1062008365@qq.com
server:
  appname: AHFS
  avatarmaxheight: 256
  avatarmaxwidth: 256
  avataruploadpath: F:\GOWorkspace\services\ahfs\bin\data\avatar
  domain: localhost
  enableletsencrypt: false
  fileuploadpath: F:\GOWorkspace\services\ahfs\bin\data\file
  httpaddr: 0.0.0.0
  httpport: "6270"
  letsencryptdir: https
  letsencrypttos: false
  mode: debug
  rooturl: http://localhost:6270
service:
  activecodelive: 15m0s
  avatarmaxsize: 3145728
  maxfilecapacitysize: 536870912
  registeremailconfirm: true
  resetpasswordcodelive: 10m0s
session:
  cookiename: ahfs_lalala
  cookiepath: /
  domain: ""
  httponly: true
  maxage: 86400
  provider: memory
  providerconfig: ""
  secure: false
