api:
  default_paging_size: 16
  max_paging_size: 32
cache:
  adapter: memory
  enabled: true
  interval: 1m0s
  ttl: 24h0m0s
database:
  driver: sqlite3
  max_idle_conns: 0
  max_life_time: 0s
  max_open_conns: 0
  url: /db/gorm.db
log:
  base:
    encoding: console
  loggers:
    console:
      provider: console
mailer:
  cert_file: ""
  certfile: ""
  enabled: true
  from: ""
  host: smtp.qq.com:465
  is_tls_enable: false
  key_file: ""
  password: jqquapwzvqctbbed
  queue_length: 512
  send_as_plain_text: false
  skip_verify: true
  subject_prefix: ""
  use_certificate: false
  username: 1062008365@qq.com
metrics:
  enabled: true
  token: ""
pprof:
  enabled: true
  http_addr: 0.0.0.0
  http_port: "6060"
server:
  app_name: AHFS
  avatar_max_height: 256
  avatar_max_width: 256
  avatar_upload_path: F:\GOWorkspace\services\ahfs\bin\data\avatar
  domain: localhost
  enable_lets_encrypt: false
  file_upload_path: F:\GOWorkspace\services\ahfs\bin\data\file
  http_addr: 0.0.0.0
  http_port: "6270"
  lets_encrypt_dir: https
  lets_encrypt_tos: false
  mode: debug
  password_complexity: []
  root_url: 'http://localhost:'
service:
  active_code_interval: 1m0s
  active_code_live: 15m0s
  avatar_max_size: 3145728
  max_file_capacity_size: 536870912
  register_email_confirm: true
  reset_password_code_interval: 1m0s
  reset_password_code_live: 10m0s
session:
  cookie_name: ahfs_lalala
  cookie_path: /
  domain: ""
  http_only: true
  max_age: 86400
  provider: memory
  provider_config: ""
  secure: false
